apiVersion: v1
kind: Service
metadata:
  name: "node-ts-example"
  labels:
    chart: "node-ts-example-1.0.0"
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: "node-ts-example-selector"